
# file: ibert_ultrascale_gth_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT 7Series
##  /   /         Filename : example_ibert_ultrascale_gth_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT 7Series 
##**************************************************************************
set_property ES_EYE_SCAN_EN TRUE [get_cells QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel]
##
## TX/RX out clock and DMONITOR clock constraints
##
# GT X0Y16
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[0].u_ch/u_gthe3_channel/DMONITOROUT[16]}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[0].u_ch/u_gthe3_channel/DMONITOROUT[16]}]]
# GT X0Y17
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[1].u_ch/u_gthe3_channel/DMONITOROUT[16]}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[1].u_ch/u_gthe3_channel/DMONITOROUT[16]}]]
# GT X0Y18
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[2].u_ch/u_gthe3_channel/DMONITOROUT[16]}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[2].u_ch/u_gthe3_channel/DMONITOROUT[16]}]]
# GT X0Y19
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[3].u_ch/u_gthe3_channel/DMONITOROUT[16]}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[3].u_ch/u_gthe3_channel/DMONITOROUT[16]}]]
##
## GTH Channel and Common Loc constraints
##
set_property LOC GTHE3_CHANNEL_X0Y16 [get_cells QUAD[0].u_q/CH[0].u_ch/u_gthe3_channel]
set_property LOC GTHE3_CHANNEL_X0Y17 [get_cells QUAD[0].u_q/CH[1].u_ch/u_gthe3_channel]
set_property LOC GTHE3_CHANNEL_X0Y18 [get_cells QUAD[0].u_q/CH[2].u_ch/u_gthe3_channel]
set_property LOC GTHE3_CHANNEL_X0Y19 [get_cells QUAD[0].u_q/CH[3].u_ch/u_gthe3_channel]
set_property LOC GTHE3_COMMON_X0Y4 [get_cells QUAD[0].u_q/u_common/u_gthe3_common]
##
## DMONITOR clock BUFFERS location constraints
##
set_property LOC BUFGCE_X1Y96 [get_cells QUAD[0].u_q/CH[0].u_ch/u_buf_dmonitorclk]				
set_property LOC BUFGCE_X1Y97 [get_cells QUAD[0].u_q/CH[1].u_ch/u_buf_dmonitorclk]				
set_property LOC BUFGCE_X1Y98 [get_cells QUAD[0].u_q/CH[2].u_ch/u_buf_dmonitorclk]				
set_property LOC BUFGCE_X1Y99 [get_cells QUAD[0].u_q/CH[3].u_ch/u_buf_dmonitorclk]				
## Set case analysis on clock selection
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/TXRATE[*]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/RXRATE[*]]
		
		

set_case_analysis 1 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL0REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL0REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL0REFCLKSEL[2]]

set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL1REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL1REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gthe3_common/QPLL1REFCLKSEL[2]]

set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/CPLLREFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/CPLLREFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/CPLLREFCLKSEL[2]]

	
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/TXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/TXPLLCLKSEL[1]]
		
	
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/RXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gthe3_channel/RXPLLCLKSEL[1]]

set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/TXOUTCLKSEL[2]]
set_case_analysis 1 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/TXOUTCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/TXOUTCLKSEL[0]]

set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/RXOUTCLKSEL[2]]
set_case_analysis 1 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/RXOUTCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gthe3_channel/RXOUTCLKSEL[0]]
